Repository graalvm/native-build-tools, pull requests merged in 2021-07, with the labels that each got.

#86 Skip Maven native testing when there is no test
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeTestMojo.java
Labels: oca-signed

#91 Fix identification of the GraalVM executable
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/tasks/BuildNativeImageTask.java
Labels: bug, oracle-emp

#94 Remove test discovery mode from the maven plugin
  common/junit-platform-native/src/main/java/org/graalvm/junit/platform/JUnitPlatformFeature.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeTestMojo.java
  samples/java-application-with-tests/pom.xml
Labels: oca-signed

#95 Remove unused scripts
  common/docs/ANNOUNCEMENT.md
  common/scripts/buildAll.sh
  common/scripts/createReleaseZip.sh
  common/scripts/testAll.sh
Labels: oracle-emp

#96 Introduce a command line argument provider for building native image options
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/dsl/NativeImageOptions.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/internal/NativeImageCommandLineProvider.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/tasks/BuildNativeImageTask.java
Labels: enhancement, oracle-emp

#114 Fix Gradle plugin groups
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/tasks/BuildNativeImageTask.java
Labels: bug, gradle-plugin, oca-signed
