Repository graalvm/native-build-tools, pull requests merged in 2022-08, with the labels that each got.

#278 Fix how the GRAALVM_QUICK_BUILD env var is read
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImageService.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/internal/BaseNativeImageOptions.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/internal/GraalVMLogger.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/tasks/BuildNativeImageTask.java
Labels: bug, OCA Verified

#280 Make it possible to pass env vars to the builder process
  docs/src/docs/asciidoc/index.adoc
  native-gradle-plugin/src/functionalTest/groovy/org/graalvm/buildtools/gradle/JavaApplicationFunctionalTest.groovy
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/dsl/NativeImageOptions.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/internal/BaseNativeImageOptions.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/internal/DeprecatedNativeImageOptions.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/tasks/BuildNativeImageTask.java
  samples/java-application-with-custom-packaging/pom.xml
  samples/java-application/src/main/java/org/graalvm/demo/Application.java
Labels: bug, gradle-plugin, OCA Verified

#274 Maven plugin fixes
  common/utils/src/main/java/org/graalvm/buildtools/utils/FileUtils.java
  common/utils/src/main/java/org/graalvm/buildtools/utils/NativeImageUtils.java
  docs/src/docs/asciidoc/index.adoc
  docs/src/docs/asciidoc/maven-plugin.adoc
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/internal/NativeImageCommandLineProvider.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/tasks/BuildNativeImageTask.java
  native-maven-plugin/build-plugins/src/main/java/org/graalvm/build/maven/MavenTask.java
  native-maven-plugin/build.gradle.kts
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/JavaApplicationFunctionalTest.groovy
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/JavaApplicationWithAgentFunctionalTest.groovy
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/AbstractNativeMojo.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeCompileMojo.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeCompileNoForkMojo.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeExtension.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeTestMojo.java
  native-maven-plugin/src/seeding-build/pom.xml
  native-maven-plugin/src/testFixtures/groovy/org/graalvm/buildtools/maven/AbstractGraalVMMavenFunctionalTest.groovy
Labels: OCA Verified

#281 Add support for `test-jar` artifacts
  .github/workflows/deploy-documentation.yml
  .github/workflows/deploy-snapshots.yml
  .github/workflows/test-native-gradle-plugin.yml
  .github/workflows/test-native-maven-plugin.yml
  docs/src/docs/asciidoc/announcement.adoc
  docs/src/docs/asciidoc/maven-plugin.adoc
  native-maven-plugin/reproducers/issue-144/pom.xml
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/JavaApplicationFunctionalTest.groovy
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/AbstractNativeMojo.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/DeprecatedNativeBuildMojo.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeCompileNoForkMojo.java
  samples/java-application-with-reflection/pom.xml
  samples/java-application-with-resources/pom.xml
  samples/java-application-with-tests/pom.xml
  samples/java-application/pom.xml
  samples/java-library/pom.xml
  samples/metadata-repo-integration/pom.xml
  samples/native-config-integration/pom.xml
Labels: OCA Verified

#286 Add Gradle CLI options for quick build and debugging
  docs/src/docs/asciidoc/gradle-plugin.adoc
  docs/src/docs/snippets/gradle/groovy/build.gradle
  docs/src/docs/snippets/gradle/kotlin/build.gradle.kts
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/tasks/BuildNativeImageTask.java
Labels: gradle-plugin, OCA Verified

#290 Add a changelog and docs about build -> compile-no-fork changes
  docs/src/docs/asciidoc/index.adoc
Labels: documentation, maven-plugin, OCA Verified

#244 Try to fix snapshot publishing
  build-logic/aggregator/build.gradle.kts
  build-logic/aggregator/src/main/kotlin/org.graalvm.build.aggregator.gradle.kts
  build-logic/aggregator/src/main/kotlin/org/graalvm/build/tasks/AbstractGitTask.kt
  build-logic/aggregator/src/main/kotlin/org/graalvm/build/tasks/GitAdd.kt
  build-logic/aggregator/src/main/kotlin/org/graalvm/build/tasks/GitClone.kt
  build-logic/aggregator/src/main/kotlin/org/graalvm/build/tasks/GitCommit.kt
  build-logic/aggregator/src/main/kotlin/org/graalvm/build/tasks/GitPush.kt
  build-logic/aggregator/src/main/kotlin/org/graalvm/build/tasks/GitReset.kt
  build-logic/common-plugins/src/main/kotlin/org.graalvm.build.publishing.gradle.kts
  gradle/libs.versions.toml
Labels: oracle-emp, OCA Verified

#291 Fix javadoc and warnings
  gradle/libs.versions.toml
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/dsl/GraalVMExtension.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/dsl/GraalVMReachabilityMetadataRepositoryExtension.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/dsl/NativeImageOptions.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/dsl/NativeResourcesOptions.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/dsl/ResourceDetectionOptions.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/dsl/agent/AgentOptions.java
Labels: documentation, enhancement, gradle-plugin, OCA Verified
