Repository graalvm/native-build-tools, pull requests merged in 2022-02, with the labels that each got.

#193 Introduce skipNativeTests flag in Maven plugin
  docs/src/docs/asciidoc/gradle-plugin.adoc
  docs/src/docs/asciidoc/index.adoc
  docs/src/docs/asciidoc/maven-plugin.adoc
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/JavaApplicationWithAgentFunctionalTest.groovy
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/JavaApplicationWithTestsFunctionalTest.groovy
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeBuildMojo.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeTestMojo.java
Labels: oca-signed

#192 Fix system property breaking build cacheability
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/tasks/BuildNativeImageTask.java
Labels: bug, oracle-emp, gradle-bug

#200 Make it possible to override the classpath
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/internal/NativeImageCommandLineProvider.java
Labels: oracle-emp, gradle-plugin

#202 Upgrade to Gradle 7.4
  .github/workflows/native-gradle-plugin.yml
  common/junit-platform-native/gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.properties
  native-gradle-plugin/buildSrc/src/main/groovy/org.graalvm.build.functional-testing.gradle
  native-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
  native-maven-plugin/build-plugins/src/main/kotlin/org.graalvm.build.maven-embedder.gradle.kts
  native-maven-plugin/gradle/wrapper/gradle-wrapper.properties
Labels: oracle-emp

#205 Add support for `@arg` file
  common/utils/src/main/java/org/graalvm/buildtools/utils/NativeImageUtils.java
  docs/src/docs/asciidoc/gradle-plugin.adoc
  docs/src/docs/asciidoc/index.adoc
  docs/src/docs/asciidoc/maven-plugin.adoc
  docs/src/docs/snippets/gradle/groovy/build.gradle
  docs/src/docs/snippets/gradle/kotlin/build.gradle.kts
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/dsl/GraalVMExtension.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/internal/BaseNativeImageOptions.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/internal/NativeImageCommandLineProvider.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/tasks/BuildNativeImageTask.java
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/JavaLibraryFunctionalTest.groovy
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeBuildMojo.java
  samples/java-application-with-tests/pom.xml
  samples/java-application/pom.xml
Labels: oracle-emp

#212 Fix @arg file not being used for tests in Maven
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeTestMojo.java
  native-maven-plugin/src/testFixtures/groovy/org/graalvm/buildtools/maven/AbstractGraalVMMavenFunctionalTest.groovy
Labels: bug, oracle-emp

#217 Make it possible to use environment variables in native tests
  docs/src/docs/asciidoc/index.adoc
  native-gradle-plugin/src/functionalTest/groovy/org/graalvm/buildtools/gradle/JavaApplicationWithTestsFunctionalTest.groovy
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/tasks/NativeRunTask.java
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/JavaApplicationWithTestsFunctionalTest.groovy
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeTestMojo.java
  native-maven-plugin/src/testFixtures/groovy/org/graalvm/buildtools/maven/AbstractGraalVMMavenFunctionalTest.groovy
  samples/java-application-with-tests/pom.xml
  samples/java-application-with-tests/src/main/java/org/graalvm/demo/Calculator.java
Labels: bug

#219 Fix incorrect declaration of output directory
  native-gradle-plugin/src/functionalTest/groovy/org/graalvm/buildtools/gradle/JavaApplicationWithTestsFunctionalTest.groovy
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java
  native-gradle-plugin/src/testFixtures/groovy/org/graalvm/buildtools/gradle/fixtures/AbstractFunctionalTest.groovy
Labels: bug, gradle-plugin
