Repository graalvm/native-build-tools, pull requests merged in 2022-06, with the labels that each got.

#242 Warn about deprecated agent DSL
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/dsl/NativeImageOptions.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/dsl/agent/DeprecatedAgentOptions.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/internal/BaseNativeImageOptions.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/internal/DeprecatedNativeImageOptions.java
Labels: oracle-emp

#251 Fix wrong scope for test dependencies
  common/utils/build.gradle.kts
Labels: bug, oracle-emp

#248 Add documentation for alternative build systems.
  docs/src/docs/asciidoc/alternative-build-systems.adoc
  docs/src/docs/asciidoc/index.adoc
Labels: oracle-emp

#256 Restore `NativeImagePlugin.NATIVE_TEST_EXTENSION`
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java
Labels: bug, oracle-emp, gradle-plugin

#258 Fix JUnit annotation scanning during the image build
  common/junit-platform-native/src/main/java/org/graalvm/junit/platform/config/jupiter/JupiterConfigProvider.java
  common/junit-platform-native/src/main/java/org/graalvm/junit/platform/config/util/AnnotationUtils.java
  config/checkstyle.xml
  docs/src/docs/asciidoc/index.adoc
  samples/java-application-with-custom-packaging/pom.xml
Labels: oracle-emp

#257 Change reachability metadata fallback path
  common/jvm-reachability-metadata/src/main/java/org/graalvm/reachability/internal/index/modules/StandardLocationModuleToConfigDirectoryIndex.java
  common/jvm-reachability-metadata/src/test/java/org/graalvm/reachability/internal/FileSystemRepositoryTest.java
  common/jvm-reachability-metadata/src/test/java/org/graalvm/reachability/internal/index/artifacts/SingleModuleJsonVersionToConfigDirectoryIndexTest.java
  common/jvm-reachability-metadata/src/test/java/org/graalvm/reachability/internal/index/modules/FileSystemModuleToConfigDirectoryIndexTest.java
  common/jvm-reachability-metadata/src/test/java/org/graalvm/reachability/internal/index/modules/JsonModuleToConfigDirectoryIndexTest.java
  common/jvm-reachability-metadata/src/test/java/org/graalvm/reachability/internal/index/modules/StandardLocationModuleToConfigDirectoryIndexTest.java
  common/jvm-reachability-metadata/src/test/resources/json/artifact-1/index.json
  common/jvm-reachability-metadata/src/test/resources/json/modules/multi-dirs/index.json
  common/jvm-reachability-metadata/src/test/resources/json/modules/multi-dirs/io.netty/netty-core/placeholder.txt
  common/jvm-reachability-metadata/src/test/resources/json/modules/single-dir/index.json
  common/jvm-reachability-metadata/src/test/resources/json/modules/single-dir/io.netty/netty-core/placeholder.txt
  common/jvm-reachability-metadata/src/test/resources/repos/repo1/org/foo/1.0/reflect-config.json
  common/jvm-reachability-metadata/src/test/resources/repos/repo1/org/foo/1.1/reflect-config.json
  common/jvm-reachability-metadata/src/test/resources/repos/repo1/org/foo/index.json
  common/jvm-reachability-metadata/src/test/resources/repos/repo2/org/foo/1.0/reflect-config.json
  common/jvm-reachability-metadata/src/test/resources/repos/repo2/org/foo/1.1/reflect-config.json
  common/jvm-reachability-metadata/src/test/resources/repos/repo2/org/foo/index.json
Labels: oracle-emp

#264 Bump dependency versions
  gradle/libs.versions.toml
Labels: oracle-emp
