Repository graalvm/native-build-tools, pull requests merged in 2022-10, with the labels that each got.

#320 Add .sdkmanrc
  .sdkmanrc
Labels: OCA Verified

#323 Bump the default metadata repository version to 0.2.1
  common/utils/src/main/java/org/graalvm/buildtools/utils/SharedConstants.java
Labels: OCA Verified

#321 Fix functional tests for MacOS users
  native-maven-plugin/src/testFixtures/groovy/org/graalvm/buildtools/maven/AbstractGraalVMMavenFunctionalTest.groovy
Labels: OCA Verified

#332 Improve toolchain selection diagnostics
  docs/src/docs/asciidoc/index.adoc
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/internal/GradleUtils.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/internal/NativeImageExecutableLocator.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/tasks/BuildNativeImageTask.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/tasks/actions/MergeAgentFilesAction.java
Labels: enhancement, OCA Verified

#335 Bump metadata repository version
  gradle/libs.versions.toml
Labels: OCA Verified

#336 Fix `NoSuchFileExceptionv in `collectReachabilityMetadata` Gradle task
  common/graalvm-reachability-metadata/src/main/java/org/graalvm/reachability/DirectoryConfiguration.java
  native-gradle-plugin/src/functionalTest/groovy/org/graalvm/buildtools/gradle/ReachabilityMetadataFunctionalTest.groovy
  samples/metadata-repo-integration/build.gradle
  samples/metadata-repo-integration/gradle.properties
Labels: OCA Verified

#337 Remove use of DependencyFilter
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/AbstractNativeMojo.java
Labels: bug, OCA Verified

#341 Test and fix `--exclude-config` regression
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java
  samples/metadata-repo-integration/build.gradle
  samples/metadata-repo-integration/gradle.properties
  samples/metadata-repo-integration/pom.xml
  samples/metadata-repo-integration/settings.gradle
  samples/metadata-repo-integration/src/main/java/org/graalvm/example/Example.java
  samples/metadata-repo-integration/src/main/java/org/graalvm/example/H2Example.java
  samples/metadata-repo-integration/src/main/java/org/graalvm/example/NettyExample.java
Labels: OCA Verified

#344 Fix version bump to 0.9.17
  gradle/libs.versions.toml
  native-maven-plugin/reproducers/issue-144/pom.xml
  samples/java-application-with-custom-packaging/pom.xml
  samples/java-application-with-custom-tests/gradle.properties
  samples/java-application-with-extra-sourceset/gradle.properties
  samples/java-application-with-reflection/gradle.properties
  samples/java-application-with-reflection/pom.xml
  samples/java-application-with-resources/gradle.properties
  samples/java-application-with-resources/pom.xml
  samples/java-application-with-tests/gradle.properties
  samples/java-application-with-tests/pom.xml
  samples/java-application/gradle.properties
  samples/java-application/pom.xml
  samples/java-library/gradle.properties
  samples/java-library/pom.xml
  samples/kotlin-application-with-tests/gradle.properties
  samples/metadata-repo-integration/gradle.properties
  samples/metadata-repo-integration/pom.xml
  samples/multi-project-with-tests/gradle.properties
  samples/native-config-integration/gradle.properties
  samples/native-config-integration/pom.xml
Labels: OCA Verified

#345 Make GraalVM installation check lazy
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeExtension.java
Labels: OCA Verified

#353 Add a check for the minimal GraalVM version
  common/utils/src/main/java/org/graalvm/buildtools/utils/NativeImageUtils.java
  common/utils/src/test/java/org/graalvm/buildtools/utils/NativeImageUtilsTest.java
  docs/src/docs/asciidoc/index.adoc
  docs/src/docs/asciidoc/maven-plugin.adoc
  docs/src/docs/snippets/gradle/groovy/build.gradle
  docs/src/docs/snippets/gradle/kotlin/build.gradle.kts
  native-gradle-plugin/src/functionalTest/groovy/org/graalvm/buildtools/gradle/RequiredVersionTest.groovy
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/dsl/NativeImageOptions.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/tasks/BuildNativeImageTask.java
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/RequireVersionFunctionalTest.groovy
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/AbstractNativeImageMojo.java
  samples/java-application/pom.xml
Labels: OCA Verified
