Repository graalvm/native-build-tools, pull requests merged in 2023-10, with the labels that each got.

#515 Revert to previous version of `escapeArg()`.
  common/utils/src/main/java/org/graalvm/buildtools/utils/NativeImageUtils.java
Labels: OCA Verified

#509 Document test binary configuration
  docs/src/docs/asciidoc/gradle-plugin.adoc
  docs/src/docs/snippets/gradle/groovy/build.gradle
  docs/src/docs/snippets/gradle/kotlin/build.gradle.kts
Labels: OCA Verified

#504 Fixes the problem that `org.junit.jupiter.api.condition.EnabledOnOs` cannot be used in NativeTest
  common/junit-platform-native/src/main/java/org/graalvm/junit/platform/config/jupiter/JupiterConfigProvider.java
  common/junit-platform-native/src/test/java/org/graalvm/junit/jupiter/OSTest.java
Labels: OCA Verified

#522 Remove deprecated use of `getConvention`
  docs/src/docs/asciidoc/index.adoc
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/internal/GradleUtils.java
Labels: gradle-plugin, OCA Verified

#525 Fix toolchain documentation
  docs/src/docs/asciidoc/gradle-plugin.adoc
Labels: OCA Verified

#526 Fix h2-related tests.
  native-gradle-plugin/src/functionalTest/groovy/org/graalvm/buildtools/gradle/OfficialMetadataRepoFunctionalTest.groovy
  native-gradle-plugin/src/functionalTest/groovy/org/graalvm/buildtools/gradle/ReachabilityMetadataFunctionalTest.groovy
Labels: OCA Verified

#528 Make metadata repo Gradle test version-agnostic.
  native-gradle-plugin/src/functionalTest/groovy/org/graalvm/buildtools/gradle/OfficialMetadataRepoFunctionalTest.groovy
Labels: OCA Verified

#532 Remove redundant settings.gradle configuration
  docs/src/docs/asciidoc/gradle-plugin-quickstart.adoc
  docs/src/docs/asciidoc/gradle-plugin.adoc
  docs/src/docs/snippets/gradle/groovy/settings.gradle
  docs/src/docs/snippets/gradle/kotlin/settings.gradle.kts
  samples/java-application-with-custom-tests/settings.gradle
  samples/java-application-with-extra-sourceset/settings.gradle
  samples/java-application-with-reflection/settings.gradle
  samples/java-application-with-resources/settings.gradle
  samples/java-application-with-tests/settings.gradle
  samples/java-application/settings.gradle
  samples/java-library/settings.gradle
  samples/kotlin-application-with-tests/settings.gradle
  samples/metadata-repo-integration/settings.gradle
  samples/multi-project-with-tests/settings.gradle
  samples/native-config-integration/settings.gradle
Labels: documentation, gradle-plugin, OCA Verified

#482 Add concurrency with test array in matrix
  .github/workflows/test-native-gradle-plugin.yml
  .github/workflows/test-native-maven-plugin.yml
  build-logic/common-plugins/build.gradle.kts
  build-logic/common-plugins/src/main/groovy/org.graalvm.build.github-actions-helper.gradle
  native-gradle-plugin/build.gradle
  native-maven-plugin/build.gradle.kts
Labels: OCA Verified

#531 Reduce Time Required for Each Test Execution
  native-gradle-plugin/src/functionalTest/groovy/org/graalvm/buildtools/gradle/JavaApplicationFunctionalTest.groovy
  native-gradle-plugin/src/functionalTest/groovy/org/graalvm/buildtools/gradle/MultiProjectJavaApplicationWithTestsFunctionalTest.groovy
  native-gradle-plugin/src/testFixtures/groovy/org/graalvm/buildtools/gradle/fixtures/AbstractFunctionalTest.groovy
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/JavaApplicationFunctionalTest.groovy
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/JavaApplicationWithAgentFunctionalTest.groovy
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/JavaApplicationWithResourcesFunctionalTest.groovy
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/JavaApplicationWithTestsFunctionalTest.groovy
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/JavaLibraryFunctionalTest.groovy
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/MetadataRepositoryFunctionalTest.groovy
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/OfficialMetadataRepositoryFunctionalTest.groovy
Labels: OCA Verified
