Repository graalvm/native-build-tools, pull requests merged in 2023-04, with the labels that each got.

#420 Disable toolchain detection by default
  docs/src/docs/asciidoc/gradle-plugin.adoc
  docs/src/docs/asciidoc/index.adoc
  docs/src/docs/snippets/gradle/groovy/build.gradle
  docs/src/docs/snippets/gradle/kotlin/build.gradle.kts
  native-gradle-plugin/src/functionalTest/groovy/org/graalvm/buildtools/gradle/NativeImageOptionsTest.groovy
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/dsl/GraalVMExtension.java
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/internal/DefaultGraalVmExtension.java
Labels: gradle-plugin, OCA Verified

#421 Deprecate `requiredVersion`.
  common/utils/src/main/java/org/graalvm/buildtools/utils/NativeImageUtils.java
  common/utils/src/test/java/org/graalvm/buildtools/utils/NativeImageUtilsTest.java
  docs/src/docs/asciidoc/index.adoc
  docs/src/docs/asciidoc/maven-plugin.adoc
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/dsl/NativeImageOptions.java
  samples/java-application/pom.xml
Labels: OCA Verified

#423 Bump metadata repo version
  gradle/libs.versions.toml
Labels: OCA Verified

#426 Create release 0.9.21
  gradle/libs.versions.toml
  native-maven-plugin/reproducers/issue-144/pom.xml
  samples/java-application-with-custom-packaging/pom.xml
  samples/java-application-with-custom-tests/gradle.properties
  samples/java-application-with-extra-sourceset/gradle.properties
  samples/java-application-with-reflection/gradle.properties
  samples/java-application-with-reflection/pom.xml
  samples/java-application-with-resources/gradle.properties
  samples/java-application-with-resources/pom.xml
  samples/java-application-with-tests/gradle.properties
  samples/java-application-with-tests/pom.xml
  samples/java-application/gradle.properties
  samples/java-application/pom.xml
  samples/java-library/gradle.properties
  samples/java-library/pom.xml
  samples/kotlin-application-with-tests/gradle.properties
  samples/metadata-repo-integration/gradle.properties
  samples/metadata-repo-integration/pom.xml
  samples/multi-project-with-tests/gradle.properties
  samples/multi-project-with-tests/pom.xml
  samples/native-config-integration/gradle.properties
  samples/native-config-integration/pom.xml
Labels: OCA Verified

#425 Fix lookup of metadata repository
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java
  native-gradle-plugin/src/test/groovy/org/graalvm/buildtools/gradle/NativeImagePluginTest.groovy
Labels: bug, gradle-plugin, OCA Verified
