Repository graalvm/native-build-tools, pull requests merged in 2023-01, with the labels that each got.

#375 Introduce a `showPublications` task
  build-logic/aggregator/src/main/kotlin/org.graalvm.build.aggregator.gradle.kts
  build-logic/common-plugins/src/main/kotlin/org.graalvm.build.publishing.gradle.kts
Labels: enhancement, OCA Verified

#381 Quickstart guides for Native Image Build Tools Maven/Gradle plugins.
  docs/src/docs/asciidoc/graalvm-setup.adoc
  docs/src/docs/asciidoc/gradle-plugin-quickstart.adoc
  docs/src/docs/asciidoc/gradle-plugin.adoc
  docs/src/docs/asciidoc/maven-plugin-quickstart.adoc
  docs/src/docs/asciidoc/maven-plugin.adoc
Labels: OCA Verified

#386 Fix `NativeImageUtils#checkVersion`
  common/utils/src/main/java/org/graalvm/buildtools/utils/NativeImageUtils.java
  common/utils/src/test/java/org/graalvm/buildtools/utils/NativeImageUtilsTest.java
Labels: OCA Verified

#392 Clarify bug report templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: OCA Verified

#391 Fix deadlock when collecting metadata
  docs/src/docs/asciidoc/index.adoc
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java
Labels: bug, gradle-plugin, OCA Verified
