Repository graalvm/native-build-tools, pull requests merged in 2023-02, with the labels that each got.

#343 Add maven support for agent
  common/utils/src/main/java/org/graalvm/buildtools/agent/AgentConfiguration.java
  docs/src/docs/asciidoc/maven-plugin.adoc
  docs/src/docs/snippets/maven/metadataCopy.xml
  docs/src/docs/snippets/maven/pom.xml
  native-maven-plugin/src/functionalTest/groovy/org/graalvm/buildtools/maven/JavaApplicationWithAgentFunctionalTest.groovy
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/AbstractNativeImageMojo.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/MergeAgentFilesMojo.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/MetadataCopyMojo.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeExtension.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeTestMojo.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/config/AbstractMergeAgentFilesMojo.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/config/agent/AgentConfiguration.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/config/agent/AgentOptionsConfiguration.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/config/agent/MetadataCopyConfiguration.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/config/agent/ModesConfiguration.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/utils/AgentUtils.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/utils/NativeImageConfigurationUtils.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/utils/Utils.java
  native-maven-plugin/src/main/java/org/graalvm/buildtools/utils/Xpp3DomParser.java
  native-maven-plugin/src/testFixtures/groovy/org/graalvm/buildtools/maven/IsolatedMavenExecutor.groovy
  samples/java-application-with-reflection/pom.xml
Labels: OCA Verified

#395 Make max parallel native image builds configurable
  docs/src/docs/asciidoc/gradle-plugin.adoc
  docs/src/docs/asciidoc/index.adoc
  native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImageService.java
Labels: gradle-plugin, OCA Verified

#396 Set regex to accept both GraalVM and native-image as version names
  common/utils/src/main/java/org/graalvm/buildtools/utils/NativeImageUtils.java
  common/utils/src/test/java/org/graalvm/buildtools/utils/NativeImageUtilsTest.java
Labels: OCA Verified

#399 Add missing notes in index
  docs/src/docs/asciidoc/index.adoc
Labels: OCA Verified

#405 Change samples link, add quickstarts
  README.md
Labels: OCA Verified

#406 Fix typo
  docs/src/docs/asciidoc/maven-plugin.adoc
Labels: documentation, OCA Verified
